language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake travis
before_script:
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs  